#pragma once


// ...
#define  pKEY__DATA_AXIS_MAX				"DATA.AXIS_MAX"
#define  pKEY__DATA_ERR_RANGE				"DATA.ERR_RANGE"

#define  pKEY__DATA_LPx_MAX				    "DATA.LPx_MAX"

#define  pKEY__DATA_RCP_PARA_PM1			"DATA.RCP_PARA.PM1"
#define  pKEY__DATA_RCP_PARA_PM2			"DATA.RCP_PARA.PM2"
#define  pKEY__DATA_RCP_PARA_PM3			"DATA.RCP_PARA.PM3"
#define  pKEY__DATA_RCP_PARA_PM4			"DATA.RCP_PARA.PM4"
#define  pKEY__DATA_RCP_PARA_PM5			"DATA.RCP_PARA.PM5"
#define  pKEY__DATA_RCP_PARA_PM6			"DATA.RCP_PARA.PM6"

#define  pKEY__DATA_RCP_PARA_LL1			"DATA.RCP_PARA.LL1"
#define  pKEY__DATA_RCP_PARA_LL2			"DATA.RCP_PARA.LL2"

//
#define  pKEY__CH_TEMPLATE_FILE_PM1			"CH.TEMPLATE_FILE.PM1"
#define  pKEY__CH_TEMPLATE_FILE_PM2			"CH.TEMPLATE_FILE.PM2"
#define  pKEY__CH_TEMPLATE_FILE_PM3			"CH.TEMPLATE_FILE.PM3"
#define  pKEY__CH_TEMPLATE_FILE_PM4			"CH.TEMPLATE_FILE.PM4"
#define  pKEY__CH_TEMPLATE_FILE_PM5			"CH.TEMPLATE_FILE.PM5"
#define  pKEY__CH_TEMPLATE_FILE_PM6			"CH.TEMPLATE_FILE.PM6"

#define  pKEY__CH_TEMPLATE_FILE_LL1			"CH.TEMPLATE_FILE.LL1"
#define  pKEY__CH_TEMPLATE_FILE_LL2			"CH.TEMPLATE_FILE.LL2"

