#pragma once


// ...
#define  pKEY__DATA_INF_DIR				    "DATA.INF_DIR"
#define  pKEY__DATA_INF_FILE				"DATA.INF_FILE"

#define  pKEY__DATA_COL_WITH_NO				"DATA.COL_WIDTH.NO"
#define  pKEY__DATA_COL_WITH_NAME			"DATA.COL_WIDTH.NAME"
#define  pKEY__DATA_COL_WITH_DATA			"DATA.COL_WIDTH.DATA"
#define  pKEY__DATA_COL_WITH_CHANNEL		"DATA.COL_WIDTH.CHANNEL"

#define  pKEY__DATA_PM1_USE					"DATA.PM1_USE"
#define  pKEY__DATA_PM2_USE					"DATA.PM2_USE"
#define  pKEY__DATA_PM3_USE					"DATA.PM3_USE"
#define  pKEY__DATA_PM4_USE					"DATA.PM4_USE"
#define  pKEY__DATA_PM5_USE					"DATA.PM5_USE"
#define  pKEY__DATA_PM6_USE					"DATA.PM6_USE"

#define  pKEY__DATA_PM1_NAME				"DATA.PM1_NAME"
#define  pKEY__DATA_PM2_NAME				"DATA.PM2_NAME"
#define  pKEY__DATA_PM3_NAME				"DATA.PM3_NAME"
#define  pKEY__DATA_PM4_NAME				"DATA.PM4_NAME"
#define  pKEY__DATA_PM5_NAME				"DATA.PM5_NAME"
#define  pKEY__DATA_PM6_NAME				"DATA.PM6_NAME"

#define  pKEY__CH_PM1_GOTO_MAINT			"CH.PM1.GOTO_MAINT"
#define  pKEY__CH_PM2_GOTO_MAINT			"CH.PM2.GOTO_MAINT"
#define  pKEY__CH_PM3_GOTO_MAINT			"CH.PM3.GOTO_MAINT"
#define  pKEY__CH_PM4_GOTO_MAINT			"CH.PM4.GOTO_MAINT"
#define  pKEY__CH_PM5_GOTO_MAINT			"CH.PM5.GOTO_MAINT"
#define  pKEY__CH_PM6_GOTO_MAINT			"CH.PM6.GOTO_MAINT"
